---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cicd
  namespace: flux-system
spec:
  targetNamespace: argo-events
  interval: 5m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: cicd
  validation: client

